# Generated by Django 6.0.2 on 2026-04-12 08:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.subscriptions.constants import BASIC_TARIFF_NAME, DEFAULT_TRIAL_DAYS


def create_initial_tariffs(apps, schema_editor) -> None:
    Tariff = apps.get_model('subscriptions', 'Tariff')
    Tariff.objects.create(
        name='Trial',
        price=0.00,
        description='Trial tariff with limited features',
        billing_period='monthly',
        is_trial_tariff=True,
        trial_days=DEFAULT_TRIAL_DAYS,
        published=False,
        is_active=True,
        sort_order=0,
        can_use_base_features=True,
        can_create_ai_recipes=True,
        can_have_common_space=True,
    )
    Tariff.objects.create(
        name=BASIC_TARIFF_NAME,
        price=99.00,
        description='Basic tariff with basic features',
        billing_period='monthly',
        published=True,
        is_active=True,
        sort_order=1,
        soon=False,
        can_use_base_features=True,
        can_create_ai_recipes=False,
        can_have_common_space=False,
    )
    Tariff.objects.create(
        name='Pro',
        price=129.00,
        description='Pro tariff',
        billing_period='monthly',
        is_trial_tariff=False,
        trial_days=DEFAULT_TRIAL_DAYS,
        published=True,
        is_active=True,
        sort_order=2,
        soon=True,
        can_use_base_features=True,
        can_create_ai_recipes=True,
        can_have_common_space=False,
    )
    Tariff.objects.create(
        name='Premium',
        price=199.00,
        description='Premium tariff',
        billing_period='monthly',
        is_trial_tariff=False,
        trial_days=DEFAULT_TRIAL_DAYS,
        published=True,
        is_active=True,
        sort_order=3,
        soon=True,
        can_use_base_features=True,
        can_create_ai_recipes=True,
        can_have_common_space=True,
    )


def delete_initial_tariffs(apps, schema_editor) -> None:
    Tariff = apps.get_model('subscriptions', 'Tariff')
    Tariff.objects.all().delete()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10, verbose_name='Период оплаты')),
                ('is_trial_tariff', models.BooleanField(default=False, verbose_name='Пробный тариф')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='Дней в пробном периоде')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('soon', models.BooleanField(default=False, verbose_name='Скоро будет')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('can_use_base_features', models.BooleanField(default=True, verbose_name='Может использовать базовые функции')),
                ('can_create_ai_recipes', models.BooleanField(default=False, verbose_name='Может создавать AI рецепты')),
                ('can_have_common_space', models.BooleanField(default=False, verbose_name='Может иметь общее пространство')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order', 'price'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_trial_tariff', True)), fields=('is_trial_tariff',), name='unique_trial_tariff')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20, verbose_name='Статус')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Пробный период начался в')),
                ('days_in_trial', models.PositiveIntegerField(default=14, verbose_name='Дней в пробном периоде')),
                ('trial_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Пробный период закончился в')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Текущий период начался в')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Текущий период закончился в')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Автопродление')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено в')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.RunPython(create_initial_tariffs, delete_initial_tariffs),
    ]
