# Generated by Django 6.0.2 on 2026-04-11 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.subscriptions.constants import BASIC_TARIFF_NAME, DEFAULT_TRIAL_DAYS


def create_initial_tariffs(apps, schema_editor) -> None:
    Tariff = apps.get_model('subscriptions', 'Tariff')
    Tariff.objects.create(
        name=BASIC_TARIFF_NAME,
        price=99.00,
        description='Basic tariff with basic features',
        billing_period='monthly',
        published=True,
        is_active=True,
        sort_order=1,
        can_use_base_features=True,
        can_create_ai_recipes=False,
    )
    Tariff.objects.create(
        name='Trial',
        price=0.00,
        description='Trial tariff with limited features',
        billing_period='monthly',
        is_trial_tariff=True,
        trial_days=DEFAULT_TRIAL_DAYS,
        published=True,
        is_active=True,
        sort_order=0,
        can_use_base_features=True,
        can_create_ai_recipes=True,
    )



def delete_initial_tariffs(apps, schema_editor) -> None:
    Tariff = apps.get_model('subscriptions', 'Tariff')
    Tariff.objects.filter(name=BASIC_TARIFF_NAME).delete()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tariff Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10, verbose_name='Billing Period')),
                ('is_trial_tariff', models.BooleanField(default=False, verbose_name='Is Trial Tariff')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='Trial Days')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('can_use_base_features', models.BooleanField(default=True, verbose_name='Can Use Base Features')),
                ('can_create_ai_recipes', models.BooleanField(verbose_name='Can Create AI Recipes')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
                'ordering': ['sort_order', 'price'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_trial_tariff', True), ('is_active', True)), fields=('is_trial_tariff',), name='unique_trial_tariff')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20, verbose_name='Status')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial Started At')),
                ('days_in_trial', models.PositiveIntegerField(default=14, verbose_name='Days in Trial')),
                ('trial_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial Ended At')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Current Period Start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Current Period End')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto Renew')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.tariff', verbose_name='Tariff')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.RunPython(create_initial_tariffs, delete_initial_tariffs),
    ]
