# Generated by Django 6.0.2 on 2026-04-14 16:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='subscriptions.tariff', verbose_name='Ожидающий тариф'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('yookassa_payment_method_id', models.CharField(max_length=64, unique=True, verbose_name='ID способа оплаты в YooKassa')),
                ('payment_method_type', models.CharField(max_length=32, verbose_name='Тип метода оплаты')),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты')),
                ('card_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип карты')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID платежа в YooKassa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_for_capture', 'Waiting for Capture'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='pending', max_length=32, verbose_name='Статус')),
                ('payment_type', models.CharField(choices=[('first_payment', 'First Payment'), ('recurring', 'Recurring'), ('zero_amount_binding', 'Zero Amount Binding')], max_length=32, verbose_name='Тип платежа')),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Ключ идемпотентности')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено в')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отмены')),
                ('metadata', models.JSONField(default=dict, verbose_name='Метаданные')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.paymentmethod', verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.paymentmethod', verbose_name='Метод оплаты'),
        ),
    ]
