# Generated by Django 6.0.2 on 2026-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_paymentmethod_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('first_payment', 'First Payment'), ('recurring', 'Recurring'), ('zero_amount_binding', 'Zero Amount Binding'), ('single_payment', 'Single Payment')], max_length=32, verbose_name='Тип платежа'),
        ),
    ]
