# Generated by Django 6.0.2 on 2026-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='send_to_tax3r',
            field=models.BooleanField(default=False, verbose_name='Отправлено в Tax3r'),
        ),
    ]
