# Generated by Django 6.0.2 on 2026-05-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_payment_send_to_tax3r'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='URL для проверки чека'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_check_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Устанавливается в True после успешного получения ответа от Tax3r.', verbose_name='Отправлен ли чек в налоговую'),
        ),
    ]
