# Generated by Django 6.0.2 on 2026-06-13 07:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_payment_check_url_payment_is_check_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='description_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, verbose_name='Пункты описания'),
        ),
    ]
