# Generated by Django 6.0.2 on 2026-03-29 12:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0002_remove_dish_description_dish_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Название списка покупок')),
                ('date_from', models.DateField(verbose_name='Начало периода')),
                ('date_to', models.DateField(verbose_name='Конец периода')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='Владелец списка покупок')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Куплено')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отметки')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Добавлено вручную')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='Позиция')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_list_items', to='dishes.ingredient', verbose_name='Ингредиент')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to=settings.AUTH_USER_MODEL, verbose_name='Владелец пункта списка покупок')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist', verbose_name='Список покупок')),
            ],
            options={
                'verbose_name': 'Пункт списка покупок',
                'verbose_name_plural': 'Пункты списка покупок',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['owner', 'date_from', 'date_to'], name='idx_shop_list_owner_period'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['owner', 'shopping_list'], name='idx_shop_list_item_owner_list'),
        ),
    ]
