# Generated by Django 6.0.2 on 2026-04-05 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_remove_dish_description_dish_recipe'),
        ('shopping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(fields=('shopping_list', 'ingredient'), name='unq_ingredient_per_shop_list'),
        ),
    ]
