# Generated by Django 6.0.2 on 2026-04-07 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppinglistitem_unq_ingredient_per_shop_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='manual_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ручное количество'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
