# Generated by Django 6.0.2 on 2026-09-12 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppinglistitem_unq_ingredient_per_shop_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
