# Generated by Django 6.0.2 on 2026-04-08 11:32

import core.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_data',
            field=models.JSONField(default=dict, validators=[core.base.validators.dict_validator], verbose_name='Onboarding Data'),
        ),
    ]
