# Generated by Django 6.0.2 on 2026-05-10 14:56

import core.base.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_onboarding_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_communications',
            field=models.BooleanField(default=False, verbose_name='Marketing Communications'),
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('consent_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('marketing_communications', 'Marketing Communications'), ('payment_method_storage', 'Payment Method Storage'), ('recurring_payments', 'Recurring Payments')], help_text='Type of consent', max_length=50, verbose_name='Consent Type')),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked')], default='granted', help_text='Granted or revoked', max_length=10, verbose_name='Action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured metadata', null=True, validators=[core.base.validators.dict_validator], verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Consent Log',
                'verbose_name_plural': 'Consent Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
