# Generated by Django 6.0.2 on 2026-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_marketing_communications_consentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_is_active',
            field=models.BooleanField(default=True, verbose_name='Telegram Active'),
        ),
    ]
