# Generated by Django 6.0.2 on 2026-05-12 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_telegram_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version', models.CharField(help_text='Human-readable version label, e.g. "1.0", "2026-05-12"', max_length=50, verbose_name='Version')),
                ('content', models.TextField(help_text='Full text of the document shown to the user', verbose_name='Content')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published At')),
                ('is_active', models.BooleanField(default=True, help_text='Only active versions are shown to users', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Privacy Policy Version',
                'verbose_name_plural': 'Privacy Policy Versions',
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version', models.CharField(help_text='Human-readable version label, e.g. "1.0", "2026-05-12"', max_length=50, verbose_name='Version')),
                ('content', models.TextField(help_text='Full text of the document shown to the user', verbose_name='Content')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published At')),
                ('is_active', models.BooleanField(default=True, help_text='Only active versions are shown to users', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Terms of Service Version',
                'verbose_name_plural': 'Terms of Service Versions',
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consentlog',
            name='privacy_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to='users.privacypolicyversion', verbose_name='Privacy Policy Version'),
        ),
        migrations.AddField(
            model_name='consentlog',
            name='terms_of_service_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to='users.termsofserviceversion', verbose_name='Terms of Service Version'),
        ),
    ]
