# Generated by Django 6.0.2 on 2026-09-12 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_privacypolicyversion_termsofserviceversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacypolicyversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='termsofserviceversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
