# Generated by Django 6.0.2 on 2026-02-26 15:54

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Уникальный идентификатор категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность категории')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Уникальный идентификатор категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность категории')),
            ],
            options={
                'verbose_name': 'Категория ингредиента',
                'verbose_name_plural': 'Категории ингредиентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность блюда')),
                ('owner', models.ForeignKey(blank=True, help_text='NULL = системное блюдо, иначе пользовательское', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец блюда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='dishes.dishcategory', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Название ингредиента')),
                ('base_unit', models.CharField(choices=[('mg', 'Миллиграммы'), ('g', 'Граммы'), ('kg', 'Килограммы'), ('ml', 'Миллилитры'), ('l', 'Литры'), ('pcs', 'Штуки'), ('tsp', 'Чайные ложки'), ('tbsp', 'Столовые ложки')], max_length=10, verbose_name='Базовая единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность ингредиента')),
                ('owner', models.ForeignKey(blank=True, help_text='NULL = системный ингредиент, иначе пользовательский', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец ингредиента')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='dishes.ingredientcategory', verbose_name='Категория ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='dishes.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_in_dishes', to='dishes.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент в блюде',
                'verbose_name_plural': 'Ингредиенты в блюде',
            },
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['owner', 'name'], name='idx_dish_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_dish_global'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', False)), name='unique_dish_user'),
        ),
        migrations.AddIndex(
            model_name='dishingredient',
            index=models.Index(fields=['dish'], name='idx_dish_ingredient_dish'),
        ),
        migrations.AddIndex(
            model_name='dishingredient',
            index=models.Index(fields=['ingredient'], name='idx_dish_ingredient_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='unique_ingredient_per_dish'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['owner', 'name'], name='idx_ingredient_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_ingredient_global'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', False)), name='unique_ingredient_user'),
        ),
    ]
