# Generated by Django 6.0.2 on 2026-03-03 13:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='NULL = системное блюдо, иначе пользовательское', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='dishes.dishcategory', verbose_name='Категория блюда'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='dishes.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='NULL = системный ингредиент, иначе пользовательский', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец ингредиента'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_ingredients', to='dishes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='dishes.ingredientcategory', verbose_name='Категория ингредиента'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['owner', 'name'], name='idx_dish_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_dish_global'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', False)), name='unique_dish_user'),
        ),
        migrations.AddIndex(
            model_name='dishingredient',
            index=models.Index(fields=['dish'], name='idx_dish_ingredient_dish'),
        ),
        migrations.AddIndex(
            model_name='dishingredient',
            index=models.Index(fields=['ingredient'], name='idx_dish_ingredient_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='unique_ingredient_per_dish'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['owner', 'name'], name='idx_ingredient_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', True)), name='unique_ingredient_global'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('owner__isnull', False)), name='unique_ingredient_user'),
        ),
    ]
