# Generated by Django 6.0.2 on 2026-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, default='', verbose_name='Рецепт'),
        ),
    ]
