# Generated by Django 6.0.2 on 2026-05-24 10:32

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_remove_dish_description_dish_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dish',
            name='unique_dish_global',
        ),
        migrations.RemoveConstraint(
            model_name='dish',
            name='unique_dish_user',
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True), ('owner__isnull', True)), name='unique_dish_global'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True), ('owner__isnull', False)), name='unique_dish_user'),
        ),
    ]
