# Generated by Django 6.0.2 on 2026-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'ordering': ['dish', 'position', 'created_at'], 'verbose_name': 'Ингредиент в блюде', 'verbose_name_plural': 'Ингредиенты в блюде'},
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Позиция'),
        ),
    ]
