# Generated by Django 6.0.2 on 2026-05-30 07:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_dish_unique_dish_global_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAIDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('source_text', models.TextField(verbose_name='Исходный текст рецепта')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('parsed', 'Распознан'), ('dish_created', 'Блюдо создано'), ('failed', 'Ошибка')], default='processing', max_length=32, verbose_name='Статус')),
                ('ai_raw_response', models.JSONField(blank=True, null=True, verbose_name='Сырой ответ AI')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload формы создания блюда')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки валидации')),
                ('usage', models.JSONField(blank=True, null=True, verbose_name='OpenAI usage')),
                ('created_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='dishes.dish', verbose_name='Созданное блюдо')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ai_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'AI-черновик блюда',
                'verbose_name_plural': 'AI-черновики блюд',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='idx_ai_draft_owner_status'), models.Index(fields=['owner', 'created_at'], name='idx_ai_draft_owner_created')],
            },
        ),
    ]
