# Generated by Django 6.0.2 on 2026-06-07 08:33

import apps.dishes.models.validators
import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dishaidraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name='ingredient',
            name='idx_ingredient_owner_name',
        ),
        migrations.AlterField(
            model_name='dishaidraft',
            name='payload',
            field=models.JSONField(blank=True, null=True, validators=[apps.dishes.models.validators.DishPayloadValidator()], verbose_name='Payload формы создания блюда'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True), ('owner__isnull', True)), name='idx_ing_global_lname_active'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True), ('owner__isnull', False)), name='idx_ing_user_lname_active'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower('name'), models.Value('ё'), models.Value('е')), name='gin_trgm_ops'), condition=models.Q(('is_active', True)), name='idx_ing_norm_name_trgm_active'),
        ),
    ]
