# Generated by Django 6.0.2 on 2026-06-23 19:36

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_remove_ingredient_idx_ingredient_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dish',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower('name'), models.Value('ё'), models.Value('е')), name='gin_trgm_ops'), condition=models.Q(('is_active', True)), name='idx_dish_norm_name_trgm_active'),
        ),
    ]
