# Generated by Django 6.0.2 on 2026-09-12 12:46

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('dishes', '0006_dish_idx_dish_norm_name_trgm_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='dishingredient',
            name='idx_dish_ingredient_dish',
        ),
        RemoveIndexConcurrently(
            model_name='dishingredient',
            name='idx_dish_ingredient_ingredient',
        ),
        AddIndexConcurrently(
            model_name='dish',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['name'], name='idx_dish_name_active'),
        ),
        AddIndexConcurrently(
            model_name='dishingredient',
            index=models.Index(fields=['dish', 'position', 'created_at'], name='idx_dish_ing_dish_pos_cr'),
        ),
    ]
