# Generated by Django 6.0.2 on 2026-09-20 14:34

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_alter_dish_id_alter_dishaidraft_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_global',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_user',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True), ('owner__isnull', True)), name='unique_ingredient_global'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True), ('owner__isnull', False)), name='unique_ingredient_user'),
        ),
    ]
