# Generated by Django 6.0.2 on 2026-05-12 06:39

import core.base.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('text_str', models.TextField(help_text='см. в "Описание переменных"', max_length=4000, validators=[core.base.validators.validate_balanced_braces], verbose_name='Текс сообщения')),
                ('with_variables', models.BooleanField(default=False, verbose_name='С переменными')),
                ('variables_description', models.TextField(blank=True, null=True, verbose_name='Описание переменных')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delivered', models.BooleanField(default=True, editable=False, verbose_name='Доставлено')),
                ('delivered_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время доставки')),
                ('text_str', models.TextField(editable=False, help_text='Текстовая версия сообщения, отправленного пользователю.', verbose_name='Текст сообщения (текстовая версия)')),
                ('error_message', models.TextField(blank=True, default='', editable=False, verbose_name='Текст ошибки')),
                ('template', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='marketing.messagetemplate', verbose_name='Шаблон уведомления')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
