# Generated by Django 6.0.2 on 2026-03-14 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cooking_date', models.DateField(verbose_name='День готовки')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='Позиция внутри дня')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cooking_events', to='dishes.dish', verbose_name='Блюдо')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Событие готовки',
                'verbose_name_plural': 'События готовки',
                'ordering': ['cooking_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('date', models.DateField(verbose_name='День')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='Позиция внутри дня')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Добавлено вручную')),
                ('cooking_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_items', to='planning.cookingevent', verbose_name='Готовка-источник')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_plan_items', to='dishes.dish', verbose_name='Блюдо')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_items', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Элемент плана питания',
                'verbose_name_plural': 'Элементы плана питания',
                'ordering': ['date', 'position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cookingevent',
            index=models.Index(fields=['owner', 'cooking_date'], name='idx_cook_owner_date'),
        ),
        migrations.AddIndex(
            model_name='cookingevent',
            index=models.Index(fields=['owner', 'dish'], name='idx_cook_owner_dish'),
        ),
        migrations.AddConstraint(
            model_name='cookingevent',
            constraint=models.UniqueConstraint(fields=('owner', 'dish', 'cooking_date'), name='unique_cooking_event_per_dish_per_day'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['owner', 'date'], name='idx_meal_owner_date'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['owner', 'date', 'position'], name='idx_meal_owner_date_pos'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['cooking_event'], name='idx_meal_cooking_event'),
        ),
        migrations.AddConstraint(
            model_name='mealplanitem',
            constraint=models.UniqueConstraint(fields=('owner', 'date', 'position'), name='unique_meal_position_per_day'),
        ),
    ]
