# Generated by Django 6.0.2 on 2026-03-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cookingevent',
            name='unique_cooking_event_per_dish_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='mealplanitem',
            name='unique_meal_position_per_day',
        ),
    ]
