# Generated by Django 6.0.2 on 2026-03-14 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dishingredient_options_dishingredient_position'),
        ('planning', '0002_alter_cookingevent_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cookingevent',
            constraint=models.UniqueConstraint(fields=('owner', 'dish', 'cooking_date'), name='unique_cooking_event_per_dish_per_day'),
        ),
    ]
