# Generated by Django 6.0.2 on 2026-04-06 12:52

import core.base.abstract_models
import core.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_cookingevent_unique_cooking_event_per_dish_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingevent',
            name='color',
            field=models.CharField(default=core.base.abstract_models.get_random_color, max_length=7, validators=[core.base.validators.HexColorValidator()], verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='color',
            field=models.CharField(default=core.base.abstract_models.get_random_color, max_length=7, validators=[core.base.validators.HexColorValidator()], verbose_name='Цвет'),
        ),
    ]
