# Generated by Django 6.0.2 on 2026-09-12 12:46

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('dishes', '0007_remove_dishingredient_idx_dish_ingredient_dish_and_more'),
        ('planning', '0003_cookingevent_color_mealplanitem_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='cookingevent',
            name='idx_cook_owner_date',
        ),
        RemoveIndexConcurrently(
            model_name='cookingevent',
            name='idx_cook_owner_dish',
        ),
        RemoveIndexConcurrently(
            model_name='mealplanitem',
            name='idx_meal_owner_date',
        ),
        RemoveIndexConcurrently(
            model_name='mealplanitem',
            name='idx_meal_owner_date_pos',
        ),
        RemoveIndexConcurrently(
            model_name='mealplanitem',
            name='idx_meal_cooking_event',
        ),
        AddIndexConcurrently(
            model_name='cookingevent',
            index=models.Index(fields=['owner', 'cooking_date', 'created_at'], name='idx_cook_owner_date_cr'),
        ),
        AddIndexConcurrently(
            model_name='mealplanitem',
            index=models.Index(fields=['owner', 'date', 'position', 'created_at'], name='idx_meal_owner_date_pos_cr'),
        ),
    ]
