# Generated by Django 6.0.2 on 2026-09-12 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_cookingevent_idx_cook_owner_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
