# Generated by Django 6.0.2 on 2026-05-31 07:49

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(choices=[('text_to_dish', 'Текст в блюдо')], db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('required_variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, editable=False, verbose_name='Обязательные переменные')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
            },
        ),
    ]
